# Production Properties
# IMPORTANT: Rely on the full JDBC URL for credentials to avoid conflicts.
# In Railway/Heroku, set DATABASE_URL = jdbc:postgresql://...

spring.datasource.url=jdbc:postgresql://autorack.proxy.rlwy.net:35760/railway
spring.datasource.username=postgres
spring.datasource.password=GPZLiRTdQWsrAZgtGezaDXqytdzOtttO

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# CORS Configuration for production
cors.allowed.origins=https://examdesk.netlify.app
