# Development Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/exam_system
spring.datasource.username=postgres
spring.datasource.password=Postgresql
spring.jpa.show-sql=false

# CORS Configuration for local dev
cors.allowed.origins=http://localhost:3000
