spring.application.name=backend
server.port = ${PORT:8080}

# Default profile
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akashmarkad001@gmail.com
spring.mail.password=ubsjocnxhlkpdxen
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
# Fail fast if Redis is unreachable (2s timeout instead of default 30s)
spring.redis.connect-timeout=2000