spring.application.name=backend
server.port = ${PORT:8080}
# spring.datasource.url=jdbc:postgresql://localhost:5432/exam_system
# spring.datasource.username=postgres
# spring.datasource.password=Postgresql

spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${PGUSER}
# spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS Configuration
cors.allowed.origins=https://examdesk.netlify.app